# Generated by Django 3.0 on 2019-12-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20191209_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokter',
            name='jadwal_praktek',
            field=models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], max_length=200),
        ),
    ]
