# Generated by Django 3.0 on 2019-12-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hewan',
            name='umur',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pengunjung',
            name='nomor_telepon',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='penjaga',
            name='nomor_telepon',
            field=models.IntegerField(),
        ),
    ]
