# Generated by Django 3.0 on 2019-12-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_auto_20191209_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='nomor_telepon',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='penjaga',
            name='jadwal_jaga',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='penjaga',
            name='nomor_telepon',
            field=models.CharField(max_length=20),
        ),
    ]
