# Generated by Django 3.0 on 2019-12-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('no_telepon', models.CharField(max_length=20)),
                ('nomor_absen', models.IntegerField(default=0)),
                ('nilai_rata', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Mantee',
        ),
    ]
